---
sidebar: sidebar 
permalink: use/manage-users.html 
keywords: add users, edit users, remove users, delete users 
summary: Fügen Sie Benutzer zu Ihrem Astra Control Center-System hinzu und entfernen Sie Benutzer, die keinen Zugriff mehr auf das System haben sollten. 
---
= Benutzer managen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Sie können Benutzer Ihrer Astra Control Center-Installation über die Astra Control Center-Benutzeroberfläche hinzufügen, entfernen und bearbeiten. Sie können die Astra UI oder verwenden https://docs.netapp.com/us-en/astra-automation-2108/index.html["Das Astra API"^] Um Benutzer zu managen.



== Benutzer hinzufügen

Kontoinhaber und -Administratoren können weitere Benutzer zur Installation des Astra Control Center hinzufügen.

.Schritte
. Klicken Sie im Navigationsbereich * Konto verwalten* auf *Konto*.
. Wählen Sie die Registerkarte *Benutzer* aus.
. Wählen Sie *Benutzer Hinzufügen*.
. Geben Sie den Namen des Benutzers, die E-Mail-Adresse und ein temporäres Kennwort ein.
+
Der Benutzer muss das Passwort bei der ersten Anmeldung ändern.

. Wählen Sie eine Benutzerrolle mit den entsprechenden Systemberechtigungen aus.
+
Jede Rolle bietet die folgenden Berechtigungen:

+
** Ein *Viewer* kann Ressourcen anzeigen.
** Ein *Mitglied* verfügt über Berechtigungen für Viewer-Rollen und kann Apps und Cluster verwalten, aber Apps oder Cluster nicht verwalten oder Snapshots oder Backups löschen.
** Ein *Admin* verfügt über Berechtigungen für die Mitgliederrolle und kann alle anderen Benutzer außer dem Eigentümer hinzufügen und entfernen.
** Ein *Owner* hat Administratorrechte und kann beliebige Benutzerkonten hinzufügen und entfernen.


. Klicken Sie Auf *Hinzufügen*.




== Passwörter verwalten

Sie können Passwörter für Benutzerkonten im Astra Control Center verwalten.



=== Passwort ändern

Sie können das Passwort Ihres Benutzerkontos jederzeit ändern.

.Schritte
. Klicken Sie auf das Symbol Benutzer oben rechts im Bildschirm.
. Wählen Sie *Profil*.
. Klicken Sie auf die Dropdown-Liste *Aktionen* und wählen Sie *Passwort ändern*.
. Geben Sie ein Passwort ein, das den Anforderungen des Passworts entspricht.
. Geben Sie das Kennwort zur Bestätigung erneut ein.
. Klicken Sie auf *Passwort ändern*.




=== Kennwort eines anderen Benutzers zurücksetzen

Wenn Ihr Konto über Berechtigungen für die Administrator- oder Eigentümerrolle verfügt, können Sie Passwörter für andere Benutzerkonten sowie für Ihre eigenen zurücksetzen. Wenn Sie ein Kennwort zurücksetzen, weisen Sie ein temporäres Kennwort zu, das der Benutzer bei der Anmeldung ändern muss.

.Schritte
. Klicken Sie im Navigationsbereich * Konto verwalten* auf *Konto*.
. Wählen Sie auf der Registerkarte *Benutzer* die Dropdown-Liste in der Spalte *Status* für den Benutzer aus.
. Wählen Sie *Passwort Zurücksetzen*.
. Geben Sie ein temporäres Kennwort ein, das den Anforderungen des Passworts entspricht.
. Geben Sie das Kennwort zur Bestätigung erneut ein.
+

NOTE: Wenn sich der Benutzer beim nächsten Mal anmeldet, wird er aufgefordert, das Passwort zu ändern.

. Klicken Sie auf *Passwort zurücksetzen*.




== Ändern Sie die Rolle eines Benutzers

Benutzer mit der Rolle „Eigentümer“ können die Rolle aller Benutzer ändern, während Benutzer mit der Administratorrolle die Rolle von Benutzern ändern können, die die Rolle „Administrator“, „Mitglied“ oder „Viewer“ haben.

.Schritte
. Klicken Sie im Navigationsbereich * Konto verwalten* auf *Konto*.
. Wählen Sie auf der Registerkarte *Benutzer* die Dropdown-Liste in der Spalte *Rolle* für den Benutzer aus.
. Wählen Sie eine neue Rolle aus, und klicken Sie dann auf *Rolle ändern*, wenn Sie dazu aufgefordert werden.


.Ergebnis
Astra Control Center aktualisiert die Benutzerberechtigungen auf der Grundlage der neuen Rolle, die Sie ausgewählt haben.



== Benutzer entfernen

Benutzer mit der Eigentümer- oder Administratorrolle können jederzeit andere Benutzer aus dem Konto entfernen.

.Schritte
. Klicken Sie im Navigationsbereich * Konto verwalten* auf *Konto*.
. Aktivieren Sie auf der Registerkarte *Benutzer* das Kontrollkästchen in der Zeile jedes Benutzers, den Sie entfernen möchten.
. Klicken Sie auf *Aktionen* und wählen Sie *Benutzer entfernen*.
. Wenn Sie aufgefordert werden, bestätigen Sie den Löschvorgang, indem Sie das Wort "Entfernen" eingeben und dann auf *Ja, Benutzer entfernen* klicken.


.Ergebnis
Astra Control Center entfernt den Benutzer aus dem Konto.
