---
sidebar: sidebar 
permalink: use/update-licenses.html 
keywords: manage, licenses, licensing, Astra Control Center, add license, update license 
summary: Sie können eine Evaluierungslizenz in eine vollständige Lizenz umwandeln oder eine bestehende Evaluierung oder Volllizenz mit einer neuen Lizenz aktualisieren. 
---
= Aktualisieren einer vorhandenen Lizenz
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


Sie können eine Evaluierungslizenz in eine vollständige Lizenz umwandeln oder eine bestehende Evaluierung oder Volllizenz mit einer neuen Lizenz aktualisieren. Wenn Sie keine vollständige Lizenz besitzen, wenden Sie sich an Ihren NetApp Ansprechpartner, um eine vollständige Lizenz und eine Seriennummer zu erhalten. Sie können die Astra UI oder verwenden https://docs.netapp.com/us-en/astra-automation-2108/index.html["Das Astra API"^] Um eine vorhandene Lizenz zu aktualisieren.

.Schritte
. Loggen Sie sich auf der NetApp Support Site ein.
. Rufen Sie die Download-Seite des Astra Control Center auf, geben Sie die Seriennummer ein und laden Sie die vollständige NetApp Lizenzdatei (NLF) herunter.
. Melden Sie sich in der UI des Astra Control Center an.
. Wählen Sie in der linken Navigationsleiste *Konto* > *Lizenz*.
. Klicken Sie auf der Seite *Konto* > *Lizenz* auf das Dropdown-Menü Status der vorhandenen Lizenz und wählen Sie *Replace*.
. Navigieren Sie zu der Lizenzdatei, die Sie heruntergeladen haben.
. Wählen Sie *Hinzufügen*.


Auf der Seite *Konto* > *Lizenzen* werden Lizenzinformationen, Ablaufdatum, Lizenzseriennummer, Konto-ID und verwendete CPU-Einheiten angezeigt.
